---
title: "Tips"
categories: 
  - Application exercise
editor: visual
format: html
webr: 
  show-startup-message: false
filters:
  - webr
---

Today we'll explore the question "What best predicts what percent of the bill amount people tip at restaurants?"

# Goals

-   Build, fit, and interpret linear models with more than one predictor

-   Compute $R^2$ and adjusted $R^2$

-   Use adjusted $R^2$ for stepwise model selection

-   Evaluate predictive performance of models

# Packages

```{webr-r}
#| label: load-packages
#| message: false
webr::install("dplyr")
webr::install("ggplot2")
webr::install("tidymodels")
webr::install("scales")
webr::install("forcats")
library(dplyr)
library(ggplot2)
library(tidymodels)
library(scales)
library(forcats)
```

# Data

The data for this application exercise was collected in 2011 by a student at St. Olaf who worked at a local restaurant.[^1]

[^1]: Dahlquist, Samantha, and Jin Dong. 2011. "The Effects of Credit Cards on Tipping." Project for Statistics 212-Statistics for the Sciences, St. Olaf College.

```{webr-r}
#| label: load-data
download.file(
  "https://raw.githubusercontent.com/sta101-f23/sta101-f23.github.io/main/ae/data/tips.csv",
  "tips.csv"
)

tips <- read.csv("tips.csv")
```

The dataset has `r nrow(tips)` observations and `r ncol(tips)` columns. Each observation represents a meal by a party at the restaurant, and for each meal we know the bill amount, the tip amount, and a variety of other features like whether the payment was made on credit card or by cash, whether any alcohol was ordered, etc.

To keep the scope manageable for this application exercise, we'll only consider the following predictors:

-   `meal`: Meal of the day (`Lunch`, `Dinner`, or `Late Night`)

-   `party`: Number of people in the party

-   `alcohol`: Whether the party ordered any alcohol (`No` or `Yes`)

-   `bill`: Bill amount, in USD

We will aim to predict `tip_percentage` from these variables.

# Exploratory data analysis

## Exercise 1

Visualize the relationship between these variables.

```{webr-r}
#| label: eda
#| fig-width: 10
#| fig-asp: 0.618

# add code here
```

## Exercise 2

In a couple of sentences, describe any apparent patterns.

> Add response here.

# Strength of fit

## Exercise 3

Fit a model predicting tip percentage from bill amount. Display and interpret the model coefficients. Additionally, calculate and interpret the $R^2$ of this model.

```{webr-r}
#| label: tip-bill

# add code here
```

> Add response here.

```{webr-r}
#| label: tip-bill-glance

# add code here
```

> Add response here.

## Exercise 4

Suppose we next add `meal` as a predictor and interpret the model coefficients again.

```{webr-r}
#| label: tip-bill-meal

# add code here
```

> Add response here.

## Exercise 5

Would you expect the $R^2$ of the second model (with `bill` and `meal` as predictors) to be higher, lower, or the same as the $R^2$ for the first model (with only `bill` as the predictor)? Explain your reasoning.

> Add response here.

## Exercise 6

Fit a model predicting tip percentage from bill amount and meal, calculate its $R^2$, and comment on your guess from the previous exercise.

```{webr-r}
#| label: tip-bill-meal-glance

# add code here
```

> Add response here.

# Adjusted $R^2$

## Exercise 7

Calculate adjusted $R^2$ for the two models. Is adding `meal` to a model predicting `tip_percentage` from `bill` useful?

```{webr-r}
#| label: compare-adj-rsq

# add code here
```

> Add response here.

# Stepwise model selection

## Backward elimination

Backward elimination starts with the full model (the model that includes all potential predictor variables). Variables are eliminated one-at-a-time from the model until we cannot improve the model any further.

Procedure:

1.  Start with a model that has all predictors we consider and compute the adjusted $R^2$.

2.  Next fit every possible model with 1 fewer predictor.

3.  Compare adjusted $R^2$s to select the best model (highest adjusted $R^2$) with 1 fewer predictor.

4.  Repeat steps 2 and 3 until adjusted $R^2$ no longer increases.

## Forward selection

Forward selection is the reverse of the backward elimination technique. Instead, of eliminating variables one-at-a-time, we add variables one-at-a-time until we cannot find any variables that improve the model any further.

Procedure:

1.  Start with a model that has no predictors.

2.  Next fit every possible model with 1 additional predictor and calculate adjusted $R^2$ of each model.

3.  Compare adjusted $R^2$ values to select the best model (highest adjusted $R^2$) with 1 additional predictor.

4.  Repeat steps 2 and 3 until adjusted $R^2$ no longer increases.

## Exercise 8

Perform backward elimination to find the best model for predicting `tip_percentage` from `meal`, `party`, `alcohol`, `bill`.

```{webr-r}
#| label: backwards

# add code here
```

> Add response here.

## Exercise 9

Perform backward elimination to find the best model for predicting `tip_percentage` from `meal`, `party`, `alcohol`, `bill`.

```{webr-r}
#| label: forward

# add code here
```

> Add response here.

## Exercise 10

Fit the "best" model and interpret it.

```{webr-r}
#| label: tip-fit

# add code here
```

> Add response here.

# Predictive performance

A common way of evaluating the predictive performance of a model is to test it against new data that was not used to build the model in the first place. In machine learning, this new dataset is commonly referred to as **testing data**, and the dataset that was used to build and select the model is commonly referred to as **training data**.

Let's first load the new data.

```{webr-r}
download.file(
  "https://raw.githubusercontent.com/sta101-f23/sta101-f23.github.io/main/ae/data/tips-test.csv",
  "tips-test.csv"
)

tips_test <- read.csv("tips-test.csv")
```

There are `{webr-r} nrow(tips_test)` observations in this new dataset, and it has all the same columns as our existing dataset.

```{webr-r}
glimpse(tips_test)
```

Let's use our model to make predictions for `tip_percentage` for these new data:

```{webr-r}
#| label: tip-aug-test

# add code here
```

We can plot the predicted values of `tip_percentage` against the observed values to see how well we're doing.

```{webr-r}
#| label: tip-aug-plot

# add code here
```

We can also quantify the average error in our predictions with a measure called **root mean square error**, RMSE.

```{webr-r}
#| label: tip-aug-rmse

# add code here
```

What this value tells us is that our predictions are off by, on average, approximately \_\_\_.

Let's take a look back at the tip percentage variables in this dataset.

```{webr-r}
#| label: tip-test-hist

# add code here
```

The tips range anywhere from \_\_\_ to \_\_\_ and our predictions are off, on average, by \_\_\_. It's not great, and it's not terrible either. This, of course, is not a very technical assessment of the predictive performance of our model. There are much more formal ways of evaluating the predictive performance of a model using RMSE, but this is a good starting point for making sense of how well you're doing with your predictions.
